
<?php
    if(Utils::isAuth(true)):
?>
            <footer class="footer text-center"> 2020 &copy; Proyecto TVES </footer>
        </div>
        <!-- ============================================================== -->
        <!-- End Page Content -->
        <!-- ============================================================== -->
    </div>
    

    
    <!-- Menu Plugin JavaScript -->
    <script src="<?= assets ?>js/sidebar-nav.min.js" defer></script>
    <!-- DataTable JS -->
    <script src="<?= assets ?>js/dataTables.min.js" defer></script>
    
<?php
    endif; 
?>

    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="<?= assets ?>js/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="<?= assets ?>js/bootstrap.min.js" defer></script>
    <!-- EncryptJS -->
    <script src="<?= assets ?>js/encrypt.js" defer></script>
    <!--Toast JavaScript -->
    <script src="<?= assets ?>js/toast.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="<?= assets ?>js/main.min.js"></script>
</body>

</html>