<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png"> -->
    <title>Sistema de inventario TVES</title>
<?php
    if (Utils::isAuth(true)) :
?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Bootstrap theme Core CSS -->
    <link href="<?= assets ?>css/bootstrap.min.css" rel="stylesheet">
    <!-- animation CSS -->
    <link href="<?= assets ?>css/animate.css" rel="stylesheet">
    <!-- Data Table CSS -->
    <link rel="stylesheet" href="<?= assets ?>css/dataTables.min.css">
<?php
    endif;
?>
    <!-- Core CSS -->
    <link href="<?= assets ?>css/core.min.css" rel="stylesheet">
    <!-- Color CSS -->
    <link href="<?= assets ?>css/colors.min.css" id="theme" rel="stylesheet">
    <!-- Utils AND Toast CSS -->
    <link rel="stylesheet" href="<?= assets ?>css/util.min.css">
    <link rel="stylesheet" href="<?= assets ?>css/toast.min.css">

<?php
    if (!Utils::isAuth(true)) :
?>
        <link rel="stylesheet" href="<?= assets ?>css/login.min.css">
<?php
    endif;
?>

    <!-- Custom CSS -->
    <link href="<?= assets ?>css/style.min.css" rel="stylesheet">

</head>

<?php

if (Utils::isAuth(true)) {
?>

    <body class="fix-header">
        <!-- ============================================================== -->
        <!-- Preloader -->
        <!-- ============================================================== -->
        <div class="preloader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
            </svg>
        </div>
        <!-- ============================================================== -->
        <!-- Wrapper -->
        <!-- ============================================================== -->
        <div id="wrapper">
            <!-- ============================================================== -->
            <!-- Topbar header - style you can find in pages.scss -->
            <!-- ============================================================== -->
            <nav class="navbar navbar-default navbar-static-top m-b-0 p-0">
                <div class="navbar-header">
                    <div class="top-left-part">
                        <!-- Logo -->
                        <a class="logo" href="<?=url_base?>">
                            <!-- Logo icon image, you can use font-icon also --><b class="p-l-20">
                                <!--This is dark logo icon--><img src="<?=assets?>images/tves_banner2.png" alt="home" class="dark-logo" />
                                <!--This is light logo icon--><img src="<?=assets?>images/TVes_logo.png" height="26" alt="home" class="light-logo" />
                            </b>
                            <!-- Logo text image you can use text also --><span class="hidden-xs">
                                <!--This is dark logo text--><img src="<?=assets?>images/tves_banner2.png" alt="home" class="dark-logo" />
                                <!--This is light logo text--><img src="<?=assets?>images/tves_banner2.png" width="170" alt="home" class="light-logo" />
                            </span> </a>
                    </div>
                    <!-- /Logo -->
                    <ul class="nav navbar-top-links navbar-right pull-right">
                        <li>
                            <a class="nav-toggler open-close waves-effect waves-light hidden-md hidden-lg" href="javascript:void(0)"><i class="fa fa-bars"></i></a>
                        </li>
                        <!-- <li>
                            <form role="search" class="app-search hidden-sm hidden-xs m-r-10">
                                <input type="text" placeholder="Buscar equipo..." class="form-control"> <a href=""><i class="fa fa-search"></i></a> </form>
                        </li> -->
                        <li>
                            <a class="profile-pic" href="#">
                                <img src="<?= assets ?>images/tves.png" alt="user-img" width="36" height="36" class="img-circle">
                                <b class="hidden-xs text-capitalize"><?= $_SESSION['usuario']['nombre'] . ' ' . $_SESSION['usuario']['apellido'] ?></b>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-header -->
                <!-- /.navbar-top-links -->
                <!-- /.navbar-static-side -->

            </nav>
            <!-- End Top Navigation -->


<?php require_once './views/layouts/sidebar.phtml' ?>
            <!-- ============================================================== -->
            <!-- Page Content -->
            <!-- ============================================================== -->
            <div id="page-wrapper">
<?php
        } else {
            echo "<body>";
        }
?>